inherit_from: .rubocop_todo.yml

inherit_gem: { rubocop-rails-omakase: rubocop.yml }

inherit_mode:
  merge:
    - Exclude
    - Include

# Preferir aspas duplas
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Desativação do comentário de documentação
Style/Documentation:
  Enabled: false
